In [2]:
import pandas as pd

In [4]:
import numpy as np

In [1]:
print('hello world')

hello world

In [5]:
book = pd.read_csv("03_Library Systembook.csv")

In [6]:
customers = pd.read_csv("03_Library SystemCustomers.csv")

In [10]:
book.head(25)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,"""20/02/2023""",25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,"""24/03/2023""",21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,"""29/03/2023""",25/03/2023,2 weeks,3.0
3,4.0,The hobbit,"""02/04/2023""",25/03/2023,2 weeks,4.0
4,5.0,Dune,"""02/04/2023""",25/03/2023,2 weeks,5.0
5,6.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
6,7.0,IT,"""10/04/2063""",03/04/2023,2 weeks,6.0
7,8.0,Misery,"""15/04/2023""",03/04/2023,2 weeks,7.0
8,9.0,Catch 22,"""15/04/2023""",16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,"""20/04/2023""",24/04/2023,2 weeks,2.0
10,11.0,1984,"""23/04/2023""",27/04/2023,2 weeks,8.0
11,12.0,Little Women,"""02/04/2023""",01/05/2023,2 weeks,1.0
12,13.0,East of Eden,"""30/04/2023""",05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,"""01/05/2023""",07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,"""01/05/2023""",10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,"""15/05/2023""",01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,"""32/05/2023""",04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,"""03/06/2023""",07/06/2023,2 weeks,5.0
18,19.0,Dracula,"""10/06/2023""",10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,"""01/06/2023""",20/06/2023,2 weeks,2.0
20,21.0,NaN,"""01/06/2023""",05/06/2023,2 weeks,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
book["Book checkout"]= book["Book checkout"].str.strip().str.strip('"')

In [16]:
book["Book checkout"]= pd.to_datetime(book["Book checkout"],dayfirst = True, errors = "coerce")

In [18]:
book.head(25)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,25/03/2023,2 weeks,3.0
3,4.0,The hobbit,2023-04-02,25/03/2023,2 weeks,4.0
4,5.0,Dune,2023-04-02,25/03/2023,2 weeks,5.0
5,6.0,Little Women,2023-04-02,01/05/2023,2 weeks,1.0
6,7.0,IT,2063-04-10,03/04/2023,2 weeks,6.0
7,8.0,Misery,2023-04-15,03/04/2023,2 weeks,7.0
8,9.0,Catch 22,2023-04-15,16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,2023-04-20,24/04/2023,2 weeks,2.0
10,11.0,1984,2023-04-23,27/04/2023,2 weeks,8.0
11,12.0,Little Women,2023-04-02,01/05/2023,2 weeks,1.0
12,13.0,East of Eden,2023-04-30,05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,2023-05-01,07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,2023-05-01,10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,2023-05-15,01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,NaT,04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,2023-06-03,07/06/2023,2 weeks,5.0
18,19.0,Dracula,2023-06-10,10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,2023-06-01,20/06/2023,2 weeks,2.0
20,21.0,NaN,2023-06-01,05/06/2023,2 weeks,NaN
21,NaN,NaN,NaT,NaN,NaN,NaN
22,NaN,NaN,NaT,NaN,NaN,NaN
23,NaN,NaN,NaT,NaN,NaN,NaN
24,NaN,NaN,NaT,NaN,NaN,NaN

In [21]:
books_silver = book[book["Customer ID"].notna()]

In [23]:
display(customers)

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
3          NaN               NaN
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [22]:
display(books_silver)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,25/03/2023,2 weeks,3.0
3,4.0,The hobbit,2023-04-02,25/03/2023,2 weeks,4.0
4,5.0,Dune,2023-04-02,25/03/2023,2 weeks,5.0
5,6.0,Little Women,2023-04-02,01/05/2023,2 weeks,1.0
6,7.0,IT,2063-04-10,03/04/2023,2 weeks,6.0
7,8.0,Misery,2023-04-15,03/04/2023,2 weeks,7.0
8,9.0,Catch 22,2023-04-15,16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,2023-04-20,24/04/2023,2 weeks,2.0
10,11.0,1984,2023-04-23,27/04/2023,2 weeks,8.0
11,12.0,Little Women,2023-04-02,01/05/2023,2 weeks,1.0
12,13.0,East of Eden,2023-04-30,05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,2023-05-01,07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,2023-05-01,10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,2023-05-15,01/06/2023,2 weeks,2.0
16,17.0,The Bloody Chamber,NaT,04/06/2023,2 weeks,3.0
17,18.0,Les Miserables,2023-06-03,07/06/2023,2 weeks,5.0
18,19.0,Dracula,2023-06-10,10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,2023-06-01,20/06/2023,2 weeks,2.0

In [25]:
customers_silver  = customers[customers["Customer ID"].notna()]

In [26]:
display(customers_silver)

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [29]:
books_silver["Book Returned"]= pd.to_datetime(books_silver["Book Returned"],dayfirst = True, errors = "coerce")

C:\Users\Admin\AppData\Local\Temp\ipykernel_11972\3184760469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books_silver["Book Returned"]= pd.to_datetime(books_silver["Book Returned"],dayfirst = True, errors = "coerce")

In [27]:
customers_silver.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 8
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    8 non-null      float64
 1   Customer Name  8 non-null      object
dtypes: float64(1), object(1)
memory usage: 192.0+ bytes

In [30]:
books_silver.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      20 non-null     float64
 1   Books                   20 non-null     object
 2   Book checkout           19 non-null     datetime64[ns]
 3   Book Returned           20 non-null     datetime64[ns]
 4   Days allowed to borrow  20 non-null     object
 5   Customer ID             20 non-null     float64
dtypes: datetime64[ns](2), float64(2), object(2)
memory usage: 1.1+ KB

In [31]:
def dataEnrich(df, col1, col2, new_col="days_between"):
    df = df.copy()
    df[new_col] = (df[col2] - df[col1]).dt.days
    return df

In [32]:
def duplicateCheck(df,subset = None):
    n_dupes = df.duplicayed(subset = subset).sum()
    dupes = df[df.duplicated(subset = subset)].sum()
    print(f"{n_dupes} duplicate row(s) would be removed: "
          f"{len(dupes)} row(s) involved in duplicate groups.")
    
    return dupes.sort_values(by=subset) if subset else dupes